---
deployment:
  tasks:
    - export DEPLOYPATH=/home/elicpane/public_html/
    - /bin/cp -R . $DEPLOYPATH
    - cd $DEPLOYPATH
    - /usr/bin/npm install  # Adjust this path based on where npm is installed
    - /usr/local/bin/php /opt/cpanel/composer/bin/composer dump-autoload
    - /usr/local/bin/php /opt/cpanel/composer/bin/composer update --no-interaction
    - /usr/local/bin/php artisan migrate --force
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan cache:clear
    - /usr/local/bin/php artisan route:clear
    - /usr/local/bin/php artisan route:cache
