---
deployment:
  tasks:
    - export DEPLOYPATH=/home/elicpane/public_html/
    - /bin/cp -R . $DEPLOYPATH
    - cd $DEPLOYPATH
    - /usr/local/bin/php /opt/cpanel/composer/bin/composer du
    - /usr/local/bin/php /opt/cpanel/composer/bin/composer update --no-interaction
    - /usr/local/bin/php /opt/cpanel/ea-nodejs10/bin/npm install
    - /usr/local/bin/php artisan migrate --force
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan cache:clear
    - /usr/local/bin/php artisan route:clear
    - /usr/local/bin/php artisan route:cache
